### ISSUE TITLE
Request: Octopath Traveler CotC

### ISSUE THREAD

**Issue by MikiNana** [zigamacele/gacharevenue#3]
Hey, can you add Octopath Traveler CotC to gacharevenue?

Global (Android)
https://app.sensortower.com/overview/com.square_enix.android_googleplay.octopathw

Global (iOS)
https://app.sensortower.com/overview/1597675715

Japan (Android)
https://app.sensortower.com/overview/com.square_enix.android_googleplay.octopathj?country=JP

Japan (iOS)
https://app.sensortower.com/overview/1438083823?country=JP

Here is latest game banner that fit in the website
![image](https://github.com/zigamacele/gacharevenue/assets/82373807/fe4418d7-ed57-4b66-b30a-d4a4b6d226c9)

**Comment by zigamacele** [comment]
Hello. Thanks for the request.
I added it to the list, it will show up with next months update.
